# Generated by Django 5.1.6 on 2025-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room_name",
            field=models.CharField(default="general", max_length=100),
            preserve_default=False,
        ),
    ]
