# Generated by Django 5.1.6 on 2025-02-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_message_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room_name",
            field=models.CharField(default="general", max_length=100),
        ),
    ]
